import type { Metadata } from "next";

import { TRPCProvider } from "@/trpc/client";


export const metadata: Metadata = {
  title: "app tiles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <TRPCProvider>
    <main>{children}</main>
  </TRPCProvider>
  );
}
